DROP VIEW V_ACCOUNT_FILES;
CREATE VIEW V_ACCOUNT_FILES
AS
  SELECT af.ACCOUNT_FILE_ID, af.ACCOUNT_ID, af.LOCATION, af.NAME, af.EXTENSION, af.CREATED, af.MODIFIED, af.DATA, af.PAGE_ID, P1.PATH_ID,
         /*vp.PATH*/'/download' || '?file=' || af.ACCOUNT_FILE_ID  AS PATH_NAME
         , af.NAME || CASE WHEN af.EXTENSION like CAST('' as NVARCHAR2(1)) THEN CAST('' as NVARCHAR2(1)) ELSE '.' || af.EXTENSION END FILE_NAME
  FROM ACCOUNT_FILES af INNER JOIN PAGES pg ON af.PAGE_ID = pg.PAGE_ID
     INNER JOIN PATHS P1 ON pg.PAGE_ID = P1.PATH_ID;