DROP VIEW V_ACCOUNT_MENUS;

CREATE OR REPLACE VIEW V_ACCOUNT_MENUS
AS
SELECT AM.*,
       M.NAME,
       M.LINK,
       M.LANG_ID
  FROM (SELECT T.ACCOUNT_ID, T.MENU_ID, MAX(T.PRIORITY) AS PRIORITY
          FROM (SELECT ACCOUNT_ID, MENU_ID, PRIORITY
                  FROM ACCOUNT_MENUS
                 WHERE ACCOUNT_ID IN (SELECT ACCOUNT_ID FROM ACCOUNTS  WHERE IS_ROLE=0) 
                 UNION ALL
                SELECT AR.ACCOUNT_ID, AM.MENU_ID, AM.PRIORITY
                  FROM ACCOUNT_MENUS AM
                  JOIN ACCOUNT_ROLES AR ON AR.ROLE_ID=AM.ACCOUNT_ID
                 WHERE AM.ACCOUNT_ID IN (SELECT ACCOUNT_ID FROM ACCOUNTS WHERE IS_ROLE=1)) T
         GROUP BY T.ACCOUNT_ID, T.MENU_ID) AM
  JOIN V_MENUS M ON M.MENU_ID=AM.MENU_ID

  