DROP VIEW V_ACCOUNT_DEVICES;

CREATE OR REPLACE VIEW V_ACCOUNT_DEVICES
AS
SELECT AD.*,
       A.LOGIN,
       D.ID
  FROM ACCOUNT_DEVICES AD
  JOIN ACCOUNTS A ON A.ACCOUNT_ID=AD.ACCOUNT_ID
  JOIN DEVICES D ON D.DEVICE_ID=AD.DEVICE_ID 