DROP VIEW V_ACCOUNT_ROLES;

CREATE OR REPLACE VIEW V_ACCOUNT_ROLES
AS
SELECT AR.*,
       A1.LOGIN AS ACCOUNT_LOGIN,
       A2.LOGIN AS ROLE_LOGIN
  FROM ACCOUNT_ROLES AR
  JOIN ACCOUNTS A1 ON A1.ACCOUNT_ID=AR.ACCOUNT_ID
  JOIN ACCOUNTS A2 ON A2.ACCOUNT_ID=AR.ROLE_ID