DROP VIEW V_ACCOUNT_PAGES;

CREATE OR REPLACE VIEW V_ACCOUNT_PAGES
AS
SELECT AP.*,
       VP1.TITLE, 
       VP2.PATH AS PAGE_PATH,
       VP3.PATH
  FROM (SELECT T.ACCOUNT_ID, T.PAGE_ID, T.PATH_ID, T.ACTION
          FROM (SELECT ACCOUNT_ID, PAGE_ID, PATH_ID, ACTION
                  FROM ACCOUNT_PAGES
                 WHERE ACCOUNT_ID IN (SELECT ACCOUNT_ID FROM ACCOUNTS WHERE IS_ROLE=0) 
                    OR ACCOUNT_ID IS NULL
                 UNION ALL
                SELECT AR.ACCOUNT_ID, AP.PAGE_ID, AP.PATH_ID, AP.ACTION
                  FROM ACCOUNT_PAGES AP
                  JOIN ACCOUNT_ROLES AR ON AR.ROLE_ID=AP.ACCOUNT_ID
                 WHERE AP.ACCOUNT_ID IN (SELECT ACCOUNT_ID FROM ACCOUNTS WHERE IS_ROLE=1)) T
         GROUP BY T.ACCOUNT_ID, T.PAGE_ID, T.PATH_ID, T.ACTION) AP
  LEFT JOIN V_PAGES VP1 ON VP1.PAGE_ID=AP.PAGE_ID         
  LEFT JOIN V_PATHS VP2 ON VP2.PATH_ID=VP1.PAGE_ID 
  LEFT JOIN V_PATHS VP3 ON VP3.PATH_ID=AP.PATH_ID 