DROP VIEW V_AGREEMENTS;

CREATE OR REPLACE VIEW V_AGREEMENTS
AS
SELECT A1.*,
        A2.LOGIN,
        S.NAME AS SYSTEM_NAME
  FROM AGREEMENTS A1
  JOIN ACCOUNTS A2 ON A2.ACCOUNT_ID=A1.ACCOUNT_ID
  LEFT JOIN SYSTEMS S ON S.SYSTEM_ID=A1.SYSTEM_ID