DROP VIEW V_CACHES;

CREATE OR REPLACE VIEW V_CACHES
AS
SELECT C.*,
       P.NAME AS PATH_NAME,
       L.NAME AS LANG_NAME
  FROM CACHES C
  JOIN LANGS L ON L.LANG_ID=C.LANG_ID
  LEFT JOIN SESSIONS S ON S.SESSION_ID=C.SESSION_ID
  LEFT JOIN PATHS P ON P.PATH_ID=C.PATH_ID
  LEFT JOIN COMMS CM ON CM.COMM_ID=C.COMM_ID 