DROP VIEW V_CHANNELS;

CREATE OR REPLACE VIEW V_CHANNELS
AS
SELECT C1.*,
        C2.NAME AS PARENT_NAME,
        LEVEL AS "LEVEL"
  FROM CHANNELS C1
  LEFT JOIN CHANNELS C2 ON C2.CHANNEL_ID=C1.PARENT_ID
 START WITH C1.PARENT_ID IS NULL
CONNECT BY C1.PARENT_ID = PRIOR C1.CHANNEL_ID 