DROP VIEW V_COMMS;

CREATE OR REPLACE VIEW V_COMMS
AS
SELECT C.*,
       P.NAME AS PATH_NAME,
       P.HANDLER_TYPE AS PATH_HANDLER,
       P.PATH
  FROM COMMS C
  JOIN SESSIONS S ON S.SESSION_ID=C.SESSION_ID
  LEFT JOIN V_PATHS P ON P.PATH_ID=C.PATH_ID
  
 