DROP VIEW V_MOBILE_FILES;

CREATE OR REPLACE VIEW V_MOBILE_FILES
AS
SELECT MF.*, 
       C.DATA AS CACHE_DATA,
       DBMS_LOB.GETLENGTH(C.DATA) AS CACHE_SIZE,
       C.EXPIRED AS CACHE_EXPIRED
  FROM MOBILE_FILES MF
  LEFT JOIN CACHES C ON C.CACHE_ID=MF.CACHE_ID
  