DROP VIEW V_MOBILE_MENUS;

CREATE OR REPLACE VIEW V_MOBILE_MENUS
AS
 SELECT M1.*, 
        M2.NAME AS PARENT_NAME,
        LEVEL AS "LEVEL", 
        L.NAME AS LANG_NAME,
        CAST((CURRENT_TIMESTAMP+INTERVAL '25' DAY) AS TIMESTAMP) AS EXPIRED
        --CAST((CURRENT_TIMESTAMP+INTERVAL '1' MONTH) AS TIMESTAMP) AS EXPIRED
   FROM MOBILE_MENUS M1
   LEFT JOIN MOBILE_MENUS M2 ON M2.MOBILE_MENU_ID=M1.PARENT_ID
   LEFT JOIN LANGS L ON L.LANG_ID=M1.LANG_ID
  START WITH M1.PARENT_ID IS NULL
CONNECT BY M1.PARENT_ID = PRIOR M1.MOBILE_MENU_ID