DROP VIEW V_PAGE_MENUS;

CREATE OR REPLACE VIEW V_PAGE_MENUS
AS
SELECT T.PAGE_ID, T.ACCOUNT_ID, T.ONLY_CURRENT,
       M.*
  FROM (SELECT PM.ACCOUNT_ID, PM.PAGE_ID, T.MENU_ID, PM.ONLY_CURRENT
          FROM PAGE_MENUS PM
          JOIN (SELECT M.MENU_ID, M.PARENT_ID, M.NAME, 
                       CONNECT_BY_ROOT M.MENU_ID PARENT_MENU_ID
                  FROM MENUS M
                CONNECT BY M.PARENT_ID = PRIOR M.MENU_ID) T ON T.PARENT_MENU_ID=PM.MENU_ID
         GROUP BY PM.ACCOUNT_ID, PM.PAGE_ID, T.MENU_ID, PM.ONLY_CURRENT) T  
  JOIN V_MENUS M ON M.MENU_ID=T.MENU_ID
