DROP VIEW V_PARENT_PATHS;

CREATE OR REPLACE VIEW V_PARENT_PATHS
AS
 SELECT P.*,
        CONNECT_BY_ROOT P.PATH_ID LAST_PATH_ID,
        P1.TITLE
   FROM V_PATHS P
   LEFT JOIN PAGES P1 ON P1.PAGE_ID=P.PATH_ID
  START WITH P.PARENT_ID IS NOT NULL
CONNECT BY PRIOR P.PARENT_ID = P.PATH_ID