DROP VIEW V_PAGE_FORMS;

CREATE OR REPLACE VIEW V_PAGE_FORMS
AS
SELECT PF.*,
        CONNECT_BY_ROOT PF.PAGE_FORM_ID LAST_PAGE_FORM_ID
    FROM PAGE_FORMS PF
 --START WITH PF.PARENT_ID IS NULL
CONNECT BY PRIOR PF.PARENT_ID = PF.PAGE_FORM_ID