DROP VIEW V_PAGES;

CREATE OR REPLACE VIEW V_PAGES
AS
SELECT P.*,
        VP.PATH,
        VP.LANG_ID,
        T.NAME AS TEMPLATE_NAME,
        T.TEMPLATE_TYPE,
        T.CSS AS TEMPLATE_CSS,
        T.JS AS TEMPLATE_JS,
        T.HTML AS TEMPLATE_HTML
  FROM PAGES P
  JOIN V_PATHS VP ON VP.PATH_ID=P.PAGE_ID
  LEFT JOIN TEMPLATES T ON T.TEMPLATE_ID=P.TEMPLATE_ID