DROP VIEW V_PERMISSIONS;

CREATE OR REPLACE VIEW V_PERMISSIONS
AS
SELECT P.*, 
       PT.NAME AS PATH_NAME,
       A.LOGIN AS ACCOUNT_LOGIN
  FROM PERMISSIONS P
  JOIN PATHS PT ON PT.PATH_ID=P.PATH_ID
  LEFT JOIN ACCOUNTS A ON A.ACCOUNT_ID=P.ACCOUNT_ID 