DROP VIEW V_PROMOTIONS;


CREATE OR REPLACE VIEW V_PROMOTIONS
AS
SELECT P.*,
       PC.NAME AS COMPANY_NAME,
       PT.NAME AS TYPE_NAME
  FROM PROMOTIONS P
  JOIN PROMOTION_PRODUCTS PP ON PP.PROMOTION_PRODUCT_ID=P.PROMOTION_PRODUCT_ID
  JOIN DEVICES D ON D.DEVICE_ID=P.DEVICE_ID
  JOIN PROMOTION_COMPANIES PC ON PC.PROMOTION_COMPANY_ID=PP.PROMOTION_COMPANY_ID
  JOIN PROMOTION_TYPES PT ON PT.PROMOTION_TYPE_ID=PP.PROMOTION_TYPE_ID