DROP VIEW V_PROMOTION_COMPANIES;

CREATE OR REPLACE VIEW V_PROMOTION_COMPANIES
AS
 SELECT PC1.*, 
        PC2.NAME AS PARENT_NAME,
        LEVEL AS "LEVEL", 
        CAST((CURRENT_TIMESTAMP+INTERVAL '1' MONTH) AS TIMESTAMP) AS EXPIRED
   FROM PROMOTION_COMPANIES PC1
   LEFT JOIN PROMOTION_COMPANIES PC2 ON PC2.PROMOTION_COMPANY_ID=PC1.PARENT_ID
  START WITH PC1.PARENT_ID IS NULL
CONNECT BY PC1.PARENT_ID = PRIOR PC1.PROMOTION_COMPANY_ID