DROP VIEW V_PROMOTION_PRODUCTS;

CREATE OR REPLACE VIEW V_PROMOTION_PRODUCTS
AS 
SELECT PP.*,
       PT.NAME AS TYPE_NAME,
       PT.DESCRIPTION AS TYPE_DESCRIPTION,
       PT.AGREEMENT AS TYPE_AGREEMENT,
       PT.IMAGE AS TYPE_IMAGE,
       PT.IMAGE_EXTENSION AS TYPE_IMAGE_EXTENSION,
       PC.NAME AS COMPANY_NAME
  FROM PROMOTION_PRODUCTS PP
  JOIN PROMOTION_TYPES PT ON PT.PROMOTION_TYPE_ID=PP.PROMOTION_TYPE_ID
  JOIN PROMOTION_COMPANIES PC ON PC.PROMOTION_COMPANY_ID=PP.PROMOTION_COMPANY_ID
  