DROP VIEW V_PUBLICATIONS;

CREATE OR REPLACE VIEW V_PUBLICATIONS
AS
SELECT P.*,
        VP1.PATH,
        VP1.TITLE,
        VP1.LANG_ID,
        VP2.PATH AS IMAGE_PATH, 
        VS.NAME AS SOURCE_NAME,
        VS.IMAGE_PATH AS SOURCE_IMAGE_PATH
  FROM PUBLICATIONS P
  JOIN V_PAGES VP1 ON VP1.PAGE_ID=P.PUBLICATION_ID
  LEFT JOIN V_PATHS VP2 ON VP2.PATH_ID=P.IMAGE_ID
  LEFT JOIN V_SOURCES VS ON VS.SOURCE_ID=P.SOURCE_ID
