DROP VIEW V_SESSIONS;

CREATE OR REPLACE VIEW V_SESSIONS
AS
SELECT S.*, 
       A1.LOGIN,
       A2.LOGIN AS APPLICATION_LOGIN
  FROM SESSIONS S
  LEFT JOIN ACCOUNTS A1 ON A1.ACCOUNT_ID=S.ACCOUNT_ID
  LEFT JOIN ACCOUNTS A2 ON A2.ACCOUNT_ID=S.APPLICATION_ID 
  