create or replace TRIGGER OPEN_ALL_PDBS
AFTER STARTUP
ON DATABASE
BEGIN

  EXECUTE IMMEDIATE 'ALTER PLUGGABLE DATABASE WORK OPEN';

  EXECUTE IMMEDIATE 'ALTER PLUGGABLE DATABASE TEST OPEN';
  
  EXECUTE IMMEDIATE 'ALTER PLUGGABLE DATABASE JIRA OPEN';
  
  EXECUTE IMMEDIATE 'ALTER PLUGGABLE DATABASE BITRIX OPEN';
  
  EXECUTE IMMEDIATE 'ALTER PLUGGABLE DATABASE ACC_TEST OPEN';
END;