ALTER TABLE MOBILE_MENUS
ADD UFS INTEGER

ALTER TABLE MOBILE_MENUS
ADD PREMIER INTEGER

ALTER TABLE MOBILE_MENUS
ADD REPLACEMENTS NCLOB

UPDATE MOBILE_MENUS
SET UFS=1

UPDATE MOBILE_MENUS
SET PREMIER=0

CREATE OR REPLACE VIEW V_MOBILE_MENUS
AS
 SELECT M1.*, 
        M2.NAME AS PARENT_NAME,
        LEVEL AS "LEVEL", 
        L.NAME AS LANG_NAME,
        CAST((CURRENT_TIMESTAMP+INTERVAL '25' DAY) AS TIMESTAMP) AS EXPIRED
        --CAST((CURRENT_TIMESTAMP+INTERVAL '1' MONTH) AS TIMESTAMP) AS EXPIRED
   FROM MOBILE_MENUS M1
   LEFT JOIN MOBILE_MENUS M2 ON M2.MOBILE_MENU_ID=M1.PARENT_ID
   LEFT JOIN LANGS L ON L.LANG_ID=M1.LANG_ID
  START WITH M1.PARENT_ID IS NULL
CONNECT BY M1.PARENT_ID = PRIOR M1.MOBILE_MENU_ID

ALTER TABLE MOBILE_ACTIVITIES
ADD UFS INTEGER 

ALTER TABLE MOBILE_ACTIVITIES
ADD PREMIER INTEGER

UPDATE MOBILE_ACTIVITIES
SET UFS=1

UPDATE MOBILE_ACTIVITIES
SET PREMIER=0

CREATE OR REPLACE VIEW V_MOBILE_ACTIVITIES
AS
SELECT MA.*
  FROM MOBILE_ACTIVITIES MA
  
ALTER TABLE DEVICES
ADD COMPANY NVARCHAR2(100) 

CREATE OR REPLACE VIEW V_DEVICES
AS
SELECT *
  FROM DEVICES

