DROP TABLE ACCOUNTS;

CREATE TABLE ACCOUNTS
(
  ACCOUNT_ID NVARCHAR2(32) NOT NULL,
  CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  IS_ROLE SMALLINT DEFAULT 0 NOT NULL,
  SURNAME NVARCHAR2(100),
  NAME NVARCHAR2(100),
  PATRONYMIC NVARCHAR2(100),
  LOGIN NVARCHAR2(100) NOT NULL,
  PASS NVARCHAR2(100),
  PHONE NVARCHAR2(100),
  EMAIL NVARCHAR2(100),
  DESCRIPTION NVARCHAR2(250),
  LOCKED TIMESTAMP,
  LOCK_REASON NVARCHAR2(250),
  PRIMARY KEY (ACCOUNT_ID)
)
