DROP TABLE ACCOUNT_PAGES;

CREATE TABLE ACCOUNT_PAGES
(
  ACCOUNT_PAGE_ID NVARCHAR2(32) NOT NULL,
  ACCOUNT_ID NVARCHAR2(32),
  PAGE_ID NVARCHAR2(32) NOT NULL,
  PATH_ID NVARCHAR2(32),
  ACTION NVARCHAR2(100) NOT NULL,
  PRIMARY KEY (ACCOUNT_PAGE_ID), 
  FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (PAGE_ID) REFERENCES PAGES (PAGE_ID),
  FOREIGN KEY (PATH_ID) REFERENCES PATHS (PATH_ID)
)
 