DROP TABLE ACCOUNT_FILES;

CREATE TABLE ACCOUNT_FILES
(
  ACCOUNT_FILE_ID NVARCHAR2(32) NOT NULL,
  ACCOUNT_ID NVARCHAR2(32) NOT NULL,
  LOCATION NVARCHAR2(1000) NOT NULL,
  NAME NVARCHAR2(255) NOT NULL,
  EXTENSION NVARCHAR2(4),
  DATA BLOB,
  PATH_ID NVARCHAR2(32) NOT NULL,
  DOC_CREATED TIMESTAMP NOT NULL,
  FILE_DOWNLOADED TIMESTAMP,
  FILE_DATA_SIZE INTEGER NOT NULL,
  CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL ,
  MODIFIED TIMESTAMP,
  PRIMARY KEY (ACCOUNT_FILE_ID)
);