DROP TABLE AGREEMENTS;

CREATE TABLE AGREEMENTS
(
  AGREEMENT_ID NVARCHAR2(32) NOT NULL,
  ACCOUNT_ID NVARCHAR2(32) NOT NULL,
  CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  LOCKED TIMESTAMP,
  NAME NVARCHAR2(100) NOT NULL,
  DESCRIPTION NVARCHAR2(250),
  PRIORITY INTEGER,
  SYSTEM_ID NVARCHAR2(32),
  ID_IN_SYSTEM NVARCHAR2(100),
  PRIMARY KEY (AGREEMENT_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (SYSTEM_ID) REFERENCES SYSTEMS (SYSTEM_ID)
)
 