DROP TABLE BRANCHES;

CREATE TABLE BRANCHES
(
  BRANCH_ID NVARCHAR2(32) NOT NULL,
  LANG_ID CHAR(2) NOT NULL,
  NAME NVARCHAR2(100),
  CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  LOCKED TIMESTAMP,
  REGION NVARCHAR2(100),
  CITY NVARCHAR2(100),
  ADDRESS NCLOB,
  LATITUDE DECIMAL(12,9),
  LONGITUDE DECIMAL(12,9), 
  PRIORITY INTEGER,
  CONTACTS NCLOB,
  MAP NVARCHAR2(50),
  ID INTEGER NOT NULL,
  PRIMARY KEY(BRANCH_ID),
  FOREIGN KEY (LANG_ID) REFERENCES LANGS (LANG_ID)  
)