DROP TABLE CACHES;

CREATE TABLE CACHES 
(
  CACHE_ID NVARCHAR2(32) NOT NULL,
  SESSION_ID NVARCHAR2(32),
  PATH_ID NVARCHAR2(32),
  COMM_ID NVARCHAR2(32),
  CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  EXPIRED TIMESTAMP,
  DATA BLOB,
  HEADERS NCLOB,
  LANG_ID CHAR(2),
  REST NVARCHAR2(1000),
  PRIMARY KEY (CACHE_ID),
  FOREIGN KEY (SESSION_ID) REFERENCES SESSIONS (SESSION_ID),
  FOREIGN KEY (PATH_ID) REFERENCES PATHS (PATH_ID),
  FOREIGN KEY (COMM_ID) REFERENCES COMMS (COMM_ID),
  FOREIGN KEY (LANG_ID) REFERENCES LANGS (LANG_ID)
)