DROP TABLE CHANNELS;

CREATE TABLE CHANNELS
(
  CHANNEL_ID NVARCHAR2(32) NOT NULL,
  PARENT_ID NVARCHAR2(32),
  NAME NVARCHAR2(100) NOT NULL,
  DESCRIPTION NVARCHAR2(250),
  CLASS_NAME NVARCHAR2(150),
  LOCKED TIMESTAMP,
  PRIORITY INTEGER,
  SETTINGS NCLOB,
  QUEUE_LENGTH INTEGER,
  DIRECTION NVARCHAR2(10),
  PRIMARY KEY (CHANNEL_ID),
  FOREIGN KEY (PARENT_ID) REFERENCES CHANNELS (CHANNEL_ID)
)