DROP TABLE COMMS;

CREATE TABLE COMMS
(
  COMM_ID NVARCHAR2(32) NOT NULL,
  SESSION_ID NVARCHAR2(32) NOT NULL,
  PATH_ID NVARCHAR2(32),
  CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  FINISHED TIMESTAMP,
  DURATION DOUBLE PRECISION,
  IN_HEADERS NCLOB,
  OUT_HEADERS NCLOB, 
  IN_DATA BLOB,
  OUT_DATA BLOB,
  LANG_ID CHAR(2) NOT NULL,
  PRIMARY KEY (COMM_ID),
  FOREIGN KEY (PATH_ID) REFERENCES PATHS (PATH_ID),
  FOREIGN KEY (SESSION_ID) REFERENCES SESSIONS (SESSION_ID),
  FOREIGN KEY (LANG_ID) REFERENCES LANGS (LANG_ID)
)