DROP TABLE CONFIRMS;

CREATE TABLE CONFIRMS
(
  CONFIRM_ID NVARCHAR2(32) NOT NULL,
  SESSION_ID NVARCHAR2(32),
  ACCOUNT_ID NVARCHAR2(32),
  MESSAGE_ID NVARCHAR2(32),
  CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  BEGIN TIMESTAMP,
  END TIMESTAMP,
  LOCKED TIMESTAMP,
  CODE NVARCHAR2(100),
  CONFIRM_TYPE NVARCHAR2(150),
  PARAMS NCLOB,
  CONFIRMED TIMESTAMP,
  PATH_ID NVARCHAR2(32),
  PRIMARY KEY (CONFIRM_ID),
  FOREIGN KEY (SESSION_ID) REFERENCES SESSIONS (SESSION_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (MESSAGE_ID) REFERENCES MESSAGES (MESSAGE_ID),
  FOREIGN KEY (PATH_ID) REFERENCES PATHS (PATH_ID)
)