DROP TABLE DEVICES;


CREATE TABLE DEVICES
(
  DEVICE_ID NVARCHAR2(32) NOT NULL,
  CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  LOCKED TIMESTAMP,
  MANUFACTURER NVARCHAR2(100),
  MODEL NVARCHAR2(100),
  OS NVARCHAR2(100),
  SCREEN_SIZE NVARCHAR2(50),
  ID NVARCHAR2(100),
  VERSION NVARCHAR2(50),
  COMPANY NVARCHAR2(100),
  PRIMARY KEY (DEVICE_ID)
);