DROP TABLE FILES;

CREATE TABLE FILES
(
  FILE_ID NVARCHAR2(32) NOT NULL,
  LOCATION NVARCHAR2(1000), 
  NAME NVARCHAR2(250),
  EXTENSION NVARCHAR2(100),
  DATA BLOB,
  PRIMARY KEY (FILE_ID),
  FOREIGN KEY (FILE_ID) REFERENCES PATHS (PATH_ID)
) 