DROP TABLE MENUS;

CREATE TABLE MENUS
(
  MENU_ID NVARCHAR2(32) NOT NULL,
  PARENT_ID NVARCHAR2(32),
  LANG_ID CHAR(2),
  LINK_ID NVARCHAR2(32),
  CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL, 
  NAME NVARCHAR2(100) NOT NULL,
  DESCRIPTION NVARCHAR2(250),
  PRIORITY INTEGER,
  NEW_UP_TO TIMESTAMP,
  ICON_IMAGE BLOB,
  PROMO_IMAGE BLOB,
  INVISIBLE INTEGER,
  PATH_ID NVARCHAR2(32),
  PRIMARY KEY (MENU_ID),
  FOREIGN KEY (PARENT_ID) REFERENCES MENUS (MENU_ID),
  FOREIGN KEY (LANG_ID) REFERENCES LANGS (LANG_ID),
  FOREIGN KEY (PATH_ID) REFERENCES PATHS (PATH_ID)
)