DROP TABLE MOBILE_TABLES;

CREATE TABLE MOBILE_TABLES
(
  MOBILE_TABLE_ID INTEGER NOT NULL,
  MOBILE_MENU_ID INTEGER NOT NULL,
  LOCKED TIMESTAMP,
  NAME NVARCHAR2(100) NOT NULL,
  DESCRIPTION NVARCHAR2(250),
  COLUMNS NCLOB,
  ALIGNMENTS NCLOB,
  SQL NCLOB,
  PRIORITY INTEGER,
  PRIMARY KEY (MOBILE_TABLE_ID),
  FOREIGN KEY (MOBILE_MENU_ID) REFERENCES MOBILE_MENUS (MOBILE_MENU_ID)
)  