DROP TABLE MOBILE_ACTIVITIES;

CREATE TABLE MOBILE_ACTIVITIES
(
  MOBILE_ACTIVITY_ID INTEGER NOT NULL,
  LANG_ID CHAR(2) NOT NULL,
  CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  LOCKED TIMESTAMP,
  NAME NVARCHAR2(100),
  IMAGE BLOB,
  IMAGE_EXTENSION NVARCHAR2(100),
  URL NCLOB,
  HTML NCLOB,
  PRIORITY INTEGER,
  UFS INTEGER,
  PREMIER INTEGER,
  PRIMARY KEY (MOBILE_ACTIVITY_ID),
  FOREIGN KEY (LANG_ID) REFERENCES LANGS (LANG_ID)
)