DROP TABLE MOBILE_FILES;

CREATE TABLE MOBILE_FILES
(
  MOBILE_FILE_ID NVARCHAR2(32) NOT NULL,
  TOKEN_ID NVARCHAR2(32) NOT NULL,
  CACHE_ID NVARCHAR2(32),
  CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  LOCATION NVARCHAR2(1000), 
  NAME NVARCHAR2(250),
  EXTENSION NVARCHAR2(100),
  CONTENT_TYPE NVARCHAR2(100),
  FILE_SIZE INTEGER,
  PRIMARY KEY (MOBILE_FILE_ID),
  FOREIGN KEY (TOKEN_ID) REFERENCES TOKENS (TOKEN_ID),
  FOREIGN KEY (CACHE_ID) REFERENCES CACHES (CACHE_ID)
) 