DROP TABLE PAGE_MENUS;

CREATE TABLE PAGE_MENUS
(
  PAGE_MENU_ID NVARCHAR2(32) NOT NULL,
  PAGE_ID NVARCHAR2(32) NOT NULL,
  MENU_ID NVARCHAR2(32) NOT NULL,
  ACCOUNT_ID NVARCHAR2(32),
  ONLY_CURRENT INTEGER,
  PRIMARY KEY (PAGE_MENU_ID),
  FOREIGN KEY (PAGE_ID) REFERENCES PAGES (PAGE_ID),
  FOREIGN KEY (MENU_ID) REFERENCES MENUS (MENU_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID)
)