DROP TABLE PAGES;

CREATE TABLE PAGES
(
  PAGE_ID NVARCHAR2(32) NOT NULL,
  TEMPLATE_ID NVARCHAR2(32),
  TITLE NVARCHAR2(100) NOT NULL,
  DESCRIPTION NVARCHAR2(250),
  TAGS NVARCHAR2(1000),
  HTML NCLOB,
  PRIMARY KEY (PAGE_ID),
  FOREIGN KEY (PAGE_ID) REFERENCES PATHS (PATH_ID),
  FOREIGN KEY (TEMPLATE_ID) REFERENCES TEMPLATES (TEMPLATE_ID)
)