DROP TABLE PAGE_TABLES;

CREATE TABLE PAGE_TABLES
(
  PAGE_TABLE_ID NVARCHAR2(32) NOT NULL,
  PAGE_ID NVARCHAR2(32) NOT NULL,
  LANG_ID CHAR(2),
  TEMPLATE_ID NVARCHAR2(32),
  NAME NVARCHAR2(100) NOT NULL,
  DESCRIPTION NVARCHAR2(250),
  QUERY NCLOB NOT NULL,
  COLUMNS NCLOB,
  ALIGNMENTS NCLOB,
  FORMATS NCLOB,
  MAX_COUNT INTEGER,
  AUTO_LOAD INTEGER,
  ASYNC INTEGER,
  PRIORITY INTEGER,
  PRIMARY KEY (PAGE_TABLE_ID),
  FOREIGN KEY (PAGE_ID) REFERENCES PAGES (PAGE_ID),
  FOREIGN KEY (LANG_ID) REFERENCES LANGS (LANG_ID),
  FOREIGN KEY (TEMPLATE_ID) REFERENCES TEMPLATES (TEMPLATE_ID)
)