DROP TABLE PAGE_TABLE_FORMS;

CREATE TABLE PAGE_TABLE_FORMS
(
  PAGE_TABLE_ID NVARCHAR2(32) NOT NULL,
  PAGE_FORM_ID NVARCHAR2(32) NOT NULL,
  FILTERS NCLOB, 
  PARAMS NCLOB,
  PRIORITY INTEGER,
  PRIMARY KEY (PAGE_TABLE_ID,PAGE_FORM_ID),
  FOREIGN KEY (PAGE_TABLE_ID) REFERENCES PAGE_TABLES (PAGE_TABLE_ID),
  FOREIGN KEY (PAGE_FORM_ID) REFERENCES PAGE_FORMS (PAGE_FORM_ID)
)