DROP TABLE PAGE_FORMS;

CREATE TABLE PAGE_FORMS
(
  PAGE_FORM_ID NVARCHAR2(32) NOT NULL,
  PAGE_ID NVARCHAR2(32),
  LANG_ID CHAR(2),
  TEMPLATE_ID NVARCHAR2(32),
  NAME NVARCHAR2(100) NOT NULL,
  DESCRIPTION NVARCHAR2(250),
  PROC_NAME NVARCHAR2(100),
  FIELDS NCLOB,
  PRIORITY INTEGER,
  ASYNC INTEGER DEFAULT 0, 
  DEFAULTS NCLOB,
  REQUIREMENTS NCLOB,
  PLACEHOLDERS NCLOB,
  BUTTONS NCLOB,
  MAX_LENGTHS NCLOB,
  LISTS NCLOB,
  STYLES NCLOB,
  TRANSFORMS NCLOB,
  PARENT_ID NVARCHAR2(32),
  PRIMARY KEY (PAGE_FORM_ID),
  FOREIGN KEY (PARENT_ID) REFERENCES PAGE_FORMS (PAGE_FORM_ID),
  FOREIGN KEY (PAGE_ID) REFERENCES PAGES (PAGE_ID),
  FOREIGN KEY (LANG_ID) REFERENCES LANGS (LANG_ID),
  FOREIGN KEY (TEMPLATE_ID) REFERENCES TEMPLATES (TEMPLATE_ID)
)