DROP TABLE PATHS;

CREATE TABLE PATHS
(
  PATH_ID NVARCHAR2(32) NOT NULL,
  NAME NVARCHAR2(100) NOT NULL,
  DESCRIPTION NVARCHAR2(250),
  PRIORITY INTEGER,
  PARENT_ID NVARCHAR2(32),
  CONTENT_TYPE NVARCHAR2(100),
  LANG_ID CHAR(2),
  CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  BEGIN TIMESTAMP,
  END TIMESTAMP,
  LOCKED TIMESTAMP,
  CHECK_PERMISSIONS SMALLINT DEFAULT 0 NOT NULL,
  CACHE_TIMEOUT INTEGER DEFAULT 5,
  HANDLER VARCHAR2(100),
  LINK NVARCHAR2(1000),
  PRIMARY KEY (PATH_ID),
  FOREIGN KEY (PARENT_ID) REFERENCES PATHS (PATH_ID),
  FOREIGN KEY (LANG_ID) REFERENCES LANGS (LANG_ID)
) 