DROP TABLE PATTERNS;

CREATE TABLE PATTERNS
(
  PATTERN_ID NVARCHAR2(32) NOT NULL,
  NAME NVARCHAR2(100) NOT NULL,
  DESCRIPTION NVARCHAR2(250),
  PATTERN_TYPE NVARCHAR2(150),
  SUBJECT NVARCHAR2(250),
  BODY NCLOB,
  PRIORITY INTEGER,
  LOCKED TIMESTAMP,
  PRIMARY KEY (PATTERN_ID),
  FOREIGN KEY (LANG_ID) REFERENCES LANGS (LANG_ID)
);
