DROP TABLE PERMISSIONS;

CREATE TABLE PERMISSIONS
(
  PERMISSION_ID NVARCHAR2(32) NOT NULL,
  PATH_ID NVARCHAR2(32) NOT NULL,
  ACCOUNT_ID NVARCHAR2(32),
  ACTION NVARCHAR2(100) NOT NULL,
  ONLY_CURRENT INTEGER,
  RIGHT NVARCHAR2(100) NOT NULL,
  PRIMARY KEY (PERMISSION_ID),
  FOREIGN KEY (PATH_ID) REFERENCES PATHS (PATH_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID)
)