DROP TABLE PROMO_MENUS;

CREATE TABLE PROMO_MENUS
(
  PROMO_MENU_ID NVARCHAR2(32) NOT NULL,
  PAGE_ID NVARCHAR2(32) NOT NULL,
  LANG_ID CHAR(2),
  NAME NVARCHAR2(100) NOT NULL,
  DESCRIPTION NVARCHAR2(250), 
  PRIORITY INTEGER,
  ONLY_CURRENT INTEGER,
  PATH_ID NVARCHAR2(32) NOT NULL,
  PRIMARY KEY (PROMO_MENU_ID),
  FOREIGN KEY (PAGE_ID) REFERENCES PAGES (PAGE_ID),
  FOREIGN KEY (PATH_ID) REFERENCES PATHS (PATH_ID),
  FOREIGN KEY (LANG_ID) REFERENCES LANGS (LANG_ID)
)