DROP TABLE PROMO_BANNERS;

CREATE TABLE PROMO_BANNERS
(
  PROMO_BANNER_ID NVARCHAR2(32) NOT NULL,
  PAGE_ID NVARCHAR2(32) NOT NULL,
  IMAGE_ID NVARCHAR2(32) NOT NULL,
  LANG_ID CHAR(2),
  PATH_ID NVARCHAR2(32),
  NAME NVARCHAR2(100),
  DESCRIPTION NVARCHAR2(250), 
  PRIORITY INTEGER,
  ONLY_CURRENT INTEGER, 
  PRIMARY KEY(PROMO_BANNER_ID),
  FOREIGN KEY(PAGE_ID) REFERENCES PAGES (PAGE_ID),
  FOREIGN KEY(LANG_ID) REFERENCES LANGS (LANG_ID),
  FOREIGN KEY(IMAGE_ID) REFERENCES PATHS (PATH_ID),
  FOREIGN KEY(PATH_ID) REFERENCES PATHS (PATH_ID)
) 