DROP TABLE PROMOTION_TYPES;

CREATE TABLE PROMOTION_TYPES
(
  PROMOTION_TYPE_ID NVARCHAR2(32) NOT NULL,
  NAME NVARCHAR2(100) NOT NULL,
  DESCRIPTION NVARCHAR2(1000),
  AGREEMENT NCLOB,
  IMAGE BLOB,
  IMAGE_EXTENSION NVARCHAR2(100),
  PRIMARY KEY (PROMOTION_TYPE_ID)
)