DROP TABLE PROMOTION_COMPANIES;

CREATE TABLE PROMOTION_COMPANIES
(
  PROMOTION_COMPANY_ID NVARCHAR2(32) NOT NULL,
  PARENT_ID NVARCHAR2(32),
  NAME NVARCHAR2(100) NOT NULL,
  DESCRIPTION NVARCHAR2(250),
  APP_LINK NVARCHAR2(1000),
  LOCKED TIMESTAMP,
  PRIMARY KEY (PROMOTION_COMPANY_ID)
)