DROP TABLE PROMOTIONS;

CREATE TABLE PROMOTIONS
(
  PROMOTION_ID NVARCHAR2(32) NOT NULL,
  PROMOTION_PRODUCT_ID NVARCHAR2(32) NOT NULL,
  DEVICE_ID NVARCHAR2(32) NOT NULL,
  CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  EXPIRED TIMESTAMP,
  ACCEPTED TIMESTAMP,
  REJECTED TIMESTAMP,
  PRIMARY KEY (PROMOTION_ID),
  FOREIGN KEY (PROMOTION_PRODUCT_ID) REFERENCES PROMOTION_PRODUCTS(PROMOTION_PRODUCT_ID),
  FOREIGN KEY (DEVICE_ID) REFERENCES DEVICES(DEVICE_ID)
) 