DROP TABLE PUBLICATIONS;

CREATE TABLE PUBLICATIONS
(
  PUBLICATION_ID NVARCHAR2(32) NOT NULL,
  SOURCE_ID NVARCHAR2(32),
  IMAGE_ID NVARCHAR2(32),
  POSTED TIMESTAMP NOT NULL,
  STICK_TILL TIMESTAMP,
  EXCERPT NVARCHAR2(500) NOT NULL,
  HTML NCLOB,
  PRIMARY KEY (PUBLICATION_ID),
  FOREIGN KEY (PUBLICATION_ID) REFERENCES PAGES (PAGE_ID),
  FOREIGN KEY (SOURCE_ID) REFERENCES SOURCES (SOURCE_ID),
  FOREIGN KEY (IMAGE_ID) REFERENCES PATHS (PATH_ID)
)