DROP TABLE SESSIONS;

CREATE TABLE SESSIONS
(
  SESSION_ID NVARCHAR2(32) NOT NULL,
  ACCOUNT_ID NVARCHAR2(32),
  APPLICATION_ID NVARCHAR2(32),
  CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  LOCKED TIMESTAMP,
  LOCK_REASON NVARCHAR2(250),
  EXPIRED TIMESTAMP,
  AGENT NVARCHAR2(1000),
  IP_HOST NVARCHAR2(100),
  NEED_COMMS SMALLINT DEFAULT 1 NOT NULL,
  PRIMARY KEY (SESSION_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (APPLICATION_ID) REFERENCES ACCOUNTS (ACCOUNT_ID)
) 