DROP TABLE SUBSCRIPTIONS;

CREATE TABLE SUBSCRIPTIONS
(
  SUBSCRIPTION_ID NVARCHAR2(32) NOT NULL,
  ACCOUNT_ID NVARCHAR2(32) NOT NULL,
  LANG_ID CHAR(2) NOT NULL,
  DELIVERY_TYPE NVARCHAR2(100) NOT NULL,
  CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  STARTED TIMESTAMP,
  FINISHED TIMESTAMP,
  KEYWORD NVARCHAR2(100) NOT NULL,
  PRIMARY KEY (SUBSCRIPTION_ID),
  FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS (ACCOUNT_ID),
  FOREIGN KEY (LANG_ID) REFERENCES LANGS (LANG_ID)
)