DROP TABLE TEMPLATES;

CREATE TABLE TEMPLATES
(
  TEMPLATE_ID NVARCHAR2(32) NOT NULL,
  NAME NVARCHAR2(100) NOT NULL,
  DESCRIPTION NVARCHAR2(250),
  TEMPLATE_TYPE NVARCHAR2(100),
  CSS NCLOB,
  JS NCLOB,
  HTML NCLOB,
  PRIORITY SMALLINT,
  LOCKED TIMESTAMP,
  PRIMARY KEY (TEMPLATE_ID)
)