DROP TABLE TOKENS;


CREATE TABLE TOKENS
(
  TOKEN_ID NVARCHAR2(32) NOT NULL,
  DEVICE_ID NVARCHAR2(32) NOT NULL,
  SESSION_ID NVARCHAR2(32),
  CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
  EXPIRED TIMESTAMP,
  PRIMARY KEY (TOKEN_ID),
  FOREIGN KEY (DEVICE_ID) REFERENCES DEVICES (DEVICE_ID),
  FOREIGN KEY (SESSION_ID) REFERENCES SESSIONS (SESSION_ID)
)