DROP TYPE TO_CLIENT_MONEY;

CREATE OR REPLACE TYPE TO_CLIENT_MONEY AS OBJECT 
( 
  CURRENCY_NAME NVARCHAR2(50),
  BEFORE_BALANCE NUMERIC(15,2),
  IN_CASH NUMERIC(15,2),
  TRANSFER_PLUS NUMERIC(15,2),
  SELL_SHARES NUMERIC(15,2),
  INCOME NUMERIC(15,2),
  OTHER_RECEIPTS NUMERIC(15,2),
  OUT_CASH NUMERIC(15,2),
  TRANSFER_MINUS NUMERIC(15,2),
  BUY_SHARES NUMERIC(15,2),
  BROKER_FEES NUMERIC(15,2),
  KO_FEES NUMERIC(15,2),
  TC_FEES NUMERIC(15,2),
  DR_FEES NUMERIC(15,2),
  OTHER_CHARGES NUMERIC(15,2),
  NDFL NUMERIC(15,2),
  AFTER_BALANCE NUMERIC(15,2)
);  