DROP TYPE TO_MESSAGE;

CREATE OR REPLACE TYPE TO_MESSAGE AS OBJECT 
( 
  MESSAGE_ID NVARCHAR2(32), 
	PARENT_ID NVARCHAR2(32), 
	CREATED TIMESTAMP, 
	CREATOR_ID NVARCHAR2(32), 
	SENDER_ID NVARCHAR2(32), 
	SENDER_CONTACT NVARCHAR2(100), 
	SENDER_NAME NVARCHAR2(100), 
	RECIPIENT_ID NVARCHAR2(32), 
  RECIPIENT_NAME NVARCHAR2(100), 
	RECIPIENT_CONTACT NVARCHAR2(100), 
	SUBJECT NVARCHAR2(250), 
	BODY NCLOB, 
	SENT TIMESTAMP, 
	ERROR NCLOB, 
	PERIOD_FROM TIMESTAMP, 
	PERIOD_TO TIMESTAMP, 
	PRIORITY INTEGER, 
	DELIVERED TIMESTAMP, 
	CHANNEL_ID NVARCHAR2(32), 
	LOCK_ID NVARCHAR2(32)
);  
