DROP FUNCTION FP_CLIENT_SHARES;

CREATE OR REPLACE FUNCTION FP_CLIENT_SHARES
(
  AGREEMENT_ID NVARCHAR2,
  FROM_DATE TIMESTAMP,
  TILL_DATE TIMESTAMP 
)
RETURN TT_CLIENT_SHARES
PIPELINED
AS 
  Rec TO_CLIENT_SHARES:=TO_CLIENT_SHARES(NULL,NULL,NULL,NULL,NULL,NULL,
                                         NULL,NULL,NULL,NULL,NULL,NULL);
  Cur INTEGER; 
  F NVARCHAR2(50);
  T NVARCHAR2(50);
  s VARCHAR2(200);
  ID_IN_SYSTEM NVARCHAR2(100);
  DB_LINK VARCHAR2(100);
  S1 NVARCHAR2(1000);
BEGIN
  
  FOR Inc IN (SELECT A.ID_IN_SYSTEM, S.DB_LINK
                 FROM AGREEMENTS A
                 JOIN SYSTEMS S ON S.SYSTEM_ID=A.SYSTEM_ID
                WHERE A.AGREEMENT_ID=FP_CLIENT_SHARES.AGREEMENT_ID) LOOP
    ID_IN_SYSTEM:=Inc.ID_IN_SYSTEM;
    DB_LINK:=Inc.DB_LINK;
    EXIT;    
  END LOOP;

  IF ((ID_IN_SYSTEM IS NOT NULL) AND (DB_LINK IS NOT NULL)) THEN
  
    Cur:=DBMS_HS_PASSTHROUGH.OPEN_CURSOR@SPECTRE_UFS; 
   
    F:=TO_CHAR(FROM_DATE,q'|'DD.MM.YYYY'|'); 
    T:=TO_CHAR(TILL_DATE,q'|'DD.MM.YYYY'|');
    
    /*ID_IN_SYSTEM:=13252;  -- ID договора
    F:=TO_CHAR(to_date('01.08.2013'),q'|'DD.MM.YYYY'|');
    T:=TO_CHAR(to_date('31.08.2013'),q'|'DD.MM.YYYY'|');*/
    
    S1:='SELECT SHARE_NAME,
                SHARE_TYPE,
                SHARE_INFO,
                INCOMING,
                RECEIPTS,
                CHARGES,
                OUTGOING,
                PRICE,
                COST,
                NKD,
                NKD_SUM,
                NKD_COST
           FROM UFS_ACCOUNT_SHARES_STATUS('||ID_IN_SYSTEM||','||F||','||T||')';

    DBMS_HS_PASSTHROUGH.PARSE@SPECTRE_UFS(Cur,S1);
    
    WHILE (DBMS_HS_PASSTHROUGH.FETCH_ROW@SPECTRE_UFS(Cur)>0) LOOP
  
      DBMS_HS_PASSTHROUGH.GET_VALUE@SPECTRE_UFS(Cur,1,s);
      Rec.SHARE_NAME:=s;
      DBMS_HS_PASSTHROUGH.GET_VALUE@SPECTRE_UFS(Cur,2,s);
      Rec.SHARE_TYPE:=s;
      DBMS_HS_PASSTHROUGH.GET_VALUE@SPECTRE_UFS(Cur,3,s);
      Rec.SHARE_INFO:=s;
      DBMS_HS_PASSTHROUGH.GET_VALUE@SPECTRE_UFS(Cur,4,Rec.INCOMING);
      DBMS_HS_PASSTHROUGH.GET_VALUE@SPECTRE_UFS(Cur,5,Rec.RECEIPTS);
      DBMS_HS_PASSTHROUGH.GET_VALUE@SPECTRE_UFS(Cur,6,Rec.CHARGES);
      DBMS_HS_PASSTHROUGH.GET_VALUE@SPECTRE_UFS(Cur,7,Rec.OUTGOING);
      DBMS_HS_PASSTHROUGH.GET_VALUE@SPECTRE_UFS(Cur,8,Rec.PRICE);      
      DBMS_HS_PASSTHROUGH.GET_VALUE@SPECTRE_UFS(Cur,9,Rec.COST);      
      DBMS_HS_PASSTHROUGH.GET_VALUE@SPECTRE_UFS(Cur,10,Rec.NKD);
      DBMS_HS_PASSTHROUGH.GET_VALUE@SPECTRE_UFS(Cur,11,Rec.NKD_SUM);
      DBMS_HS_PASSTHROUGH.GET_VALUE@SPECTRE_UFS(Cur,12,Rec.NKD_COST);
      
      PIPE ROW (Rec);
      
    END LOOP;
    
    DBMS_HS_PASSTHROUGH.CLOSE_CURSOR@SPECTRE_UFS(Cur); 
    
  END IF;  
  
EXCEPTION
  WHEN OTHERS THEN DBMS_HS_PASSTHROUGH.CLOSE_CURSOR@SPECTRE_UFS(Cur); 
  RAISE;
END;