CREATE OR REPLACE FUNCTION GET_UNIQUE_ID 
RETURN NVARCHAR2
AS 
  RET NVARCHAR2(32); 
BEGIN 
  RET:=SYS_GUID(); 
  RET:=SUBSTR(RET,21,12)||SUBSTR(RET,17,4)||SUBSTR(RET,13,4)||SUBSTR(RET,9,4)||SUBSTR(RET,1,8); 
  RET:=DBMS_CRYPTO.HASH(TO_CLOB(RET),DBMS_CRYPTO.HASH_MD5);
  RETURN RET; 
END;  