DROP PROCEDURE UNLOCK_MESSAGE;

CREATE OR REPLACE PROCEDURE UNLOCK_MESSAGE
(
  MESSAGE_ID IN NVARCHAR2,
  CHANNEL_ID IN NVARCHAR2,
  SENT TIMESTAMP
)
AS 
BEGIN
  
  UPDATE MESSAGES
     SET LOCK_ID=NULL,
         CHANNEL_ID=UNLOCK_MESSAGE.CHANNEL_ID,
         SENT=DECODE(SENT,NULL,CURRENT_TIMESTAMP,SENT)
   WHERE MESSAGE_ID=UNLOCK_MESSAGE.MESSAGE_ID;
     
  COMMIT;    

END;