  <ul class="add-nav">
  <? if($menu){ ?>
    <? foreach($menu as $item){ ?>
    <li><a href="<? echo($this->phpself.'pages/'.$item->url.$this->urlsufix); ?>"><? echo($item->name); ?></a></li>
    <? } ?>
  <? } ?>
  </ul>
  <div class="cr">
    <a id="mini-logo">UFS Investment Company</a>
	        <div class="copyright">
      &copy; UFS IC <? echo(date('Y')); ?>
      <a href="<? echo($this->phpself.'pages/'.$this->global_model->pages_url('contact').$this->urlsufix); ?>" class="contacts"><? echo(dictionary('Контакты')); ?></a><br />
    </div>
   <? if($this->site_lang=='ru') { ?> 
	<div class="legal_notice">
      <p><a>Рейтинг надежности на&nbsp;уровне А,&nbsp;высокий уровень надежности (РА&nbsp;Эксперт)<span>Рейтинг надежности на уровне, &laquo;А&raquo; подтверждает высокий уровень надежности. Прогноз &laquo;стабильный&raquo; означает высокую вероятность сохранения рейтинга на&nbsp;текущем уровне в&nbsp;среднесрочной перспективе.</span></a></p> 
      <p><a>Рейтинг кредитоспособности по&nbsp;национальной шкале &laquo;А&raquo; (AK&M)<span>Рейтинг &laquo;А&raquo; означает, что компания имеет высокий уровень кредитоспособности. Риск несвоевременного выполнения обязательств низкий, вероятность реструктуризации долга или его части минимальна.</span></a></p> 
      <p><a>Дважды лауреат премии &laquo;Investor Awards&raquo;<span>&laquo;Investor Awards&raquo; вручается за&nbsp;наиболее значимые достижения в&nbsp;области инвестиций как компаниям, так и&nbsp;отдельным инвесторам. В&nbsp;2012 году UFS IC&nbsp;стала лауреатом премии в&nbsp;специальной номинации &laquo;Лучшее доверительное управление на&nbsp;рынках <nobr>fixed-income</nobr> CIS и&nbsp;ETFs & Mutual Funds (Gold)&raquo;. В&nbsp;2011 году компания получила премию в&nbsp;номинации &laquo;Сделка года. Привлечение международных инвестиций в&nbsp;компании второго и&nbsp;третьего эшелона&raquo;&nbsp;&mdash; за&nbsp;привлечение инвестиций с&nbsp;помощью структурирования займа и&nbsp;выпуска еврооблигаций для компании &laquo;ЛенСпецСМУ&raquo;.</span></a></p> 
      <p><a>Золотой диплом &laquo;За&nbsp;информационную открытость&raquo;<span>Всероссийский конкурс &laquo;Золотой диплом за&nbsp;информационную открытость&raquo; проводится с&nbsp;целью поддержать эффективное взаимодействие между российскими СМИ, государственной и&nbsp;местной властью и&nbsp;деловым сообществом. В&nbsp;2012 году UFS IC&nbsp;в&nbsp;рамках конкурса получила Специальный Золотой Диплом &laquo;За&nbsp;информационную открытость&raquo;.</span></a></p> 
      <p><a>Лауреат Национальной премии &laquo;Финансовый Олимп 2012&raquo;<span>Национальная премия &laquo;Финансовый Олимп&raquo;&nbsp;&mdash; это профессиональная награда, которой ежегодно отмечаются успехи ведущих компаний и&nbsp;<nobr>топ-менеджеров</nobr>, работающих на&nbsp;финансовом рынке России. UFS IC&nbsp;признана лучшей в&nbsp;номинации &laquo;Стратегия инвестирования. Результат и&nbsp;успех&raquo;.</span></a></p>
      <p><a>Лауреат премии Spear&rsquo;s Awards<span>Spear&rsquo;s Russian Wealth Management Awards&nbsp;&mdash; первая в&nbsp;России ежегодная Премия для лучших представителей индустрии частного банковского обслуживания, управления большими капиталами и&nbsp;смежных индустрий. В&nbsp;2013 году &quot; за&nbsp;развитие и&nbsp;продвижение идей альтернативных инвестиций UFS IC&nbsp;стала лауреатом премии в&nbsp;номинации &laquo;Золотой стандарт индустрии частного банковского обслуживания&raquo;.</span></a></p>
      <p><a>Дважды лауреат премии Cbonds Awards<span>Ежегодная премия Cbonds Awards вручается крупнейшим российским инвестиционным банкам и компаниям — лучшим участникам долгового рынка. По итогам голосования в 2014 году UFS IC стала лауреатом в номинации "Самая читаемая аналитика рынка облигаций". По итогам голосования в 2013 году UFS IC получила награды в номинациях «Прорыв года в аналитике» и лучший аналитик на рынке Fixed Income.</span></a></p></div>
    
	<? } ?>
	 <? if($this->site_lang=='en') { ?> 
	<div class="legal_notice">
             <p><a>Reliability rating at the level &laquo;A&raquo;, high level of reliability (RA Expert)<span>&laquo;Expert RA&raquo; is a Russian leading rating agency. In the rating list of the agency there are 350 active individual ratings, including 85 % of the total number of the reliability ratings. Reliability rating at the A level confirms a high level of reliability.  The forecast - &laquo;stable&raquo; means a high probability of saving the rating at the current level in the medium term.</span></a></p>
             <p><a>Creditworthiness rating according to the national scale &laquo;A&raquo; (AK&M)<span>The rating AK&M is an integrated evaluation of the investment or managing company&rsquo;s capability for complete and due fulfillment of its obligations. The rating &laquo;A&raquo; means that the company has a high level of creditworthiness. The risk of undue fulfillment of the obligations is low; the probability of debt or part of the debt conversion is minimal. </span></a></p>
             <p><a>Twice laureate of the prize &laquo;Investor Awards&raquo;<span>&laquo;Investor Awards&raquo; is presented to the companies as well as to the individual investors for the most important achievements in the investment sphere.  In 2011 UFS IC received the price in the nomination &laquo;The year’s transaction. Attraction of the international investments to the companies of the second and third range&raquo;, for attracting investments by means of borrowings structuring and Eurobonds emission for the company &laquo;LenSpetsSMU&raquo;. In 2012 UFS IC became a prize-winner in the special nomination &laquo;The best trust management on the markets fixed-income CIS and ETFs & Mutual Funds (Gold)&raquo;. </span></a></p>		       
             <p><a>Golden diploma &laquo;For the informational transparency&raquo;<span>The All-Russian competition &laquo;golden diploma for the informational transparency&raquo; is held in order to support an effective interaction between Russian mass media, state and local authorities and business community. In 2012 as part of the competition UFS IC received the special golden diploma &laquo;For the informational transparency&raquo;.</span></a></p>
             <p><a>Laureate of the national prize &laquo;Financial Olympus&raquo;<span>The national prize &laquo;Financial Olympus&raquo; is an annual professional prize which marks the merits of the leading companies and top-managers on the financial market of Russia. IFS IC was recognized as the best company in the nomination &laquo;Investment strategy. Result and success&raquo;.</span></a></p>
             <p><a>Laureate of Spear&rsquo;s Awards<span>Spear&rsquo;s Russian Wealth Management Awards is the first Russian annual Award for the best participants in private banking, wealth management and related industries. In 2013 UFS IC became prizewinner in the category &laquo;Golden standard of the private banking industry&raquo; for development and promotion of alternative investments ideas.</span></a></p>
             <p><a>Twice laureate of Cbonds Awards<span>The annual price Cbonds Awards concerns the largest Russian investment banks and companies — the best participants in the debt market. According to 2014 voting results UFS IC won the award in the category "The most widely read research in the bond market". According to 2013 voting results UFS IC won the award in the categories “Breakthrough of the year in the research” and “The best analyst in the Fixed Income market”</span></a></p>
 
	</div>
	<? } ?>
<? if($this->site_lang=='de') { ?> 
<div class="legal_notice">
<p><a>Zuverlässigkeitsrating auf dem Niveau “A”, hohes Zuverlässigkeitsniveau (RA Expert)<span>“Experte RA” ist die führende russische Rating-Agentur. Auf dem Ratingsblatt der Agentur es gibt mehr als 350 wirkende Individualratings, einschließlich 85% der Gesamtzahl der Zuverlässigkeitsratings. Das Zuverlässigkeitsrating auf dem Niveau A bestätigt das hohe Zuverlässigkeitsniveau. Die Prognose stabil” bedeutet die hohe Wahrscheinlichkeit der Ratingserhaltung auf dem laufenden Niveau in der mittelfristigen Perspektive.</span></a></p>
<p><a>Kreditwürdigkeitsrating laut der Nationalskala “A” (AK&M)<span>Das Rating AK&M ist die Komplexbewertung der Fähigkeit der Investitions - und Managergesellschaften, ihre Pflichten völlig und rechtzeitig nachzukommen. Das Rating “A” bedeutet, das die Gesellschaft ein hohes Kreditwürdigkeitsniveau hat. Das Risiko der unzeitigen Pflichtenerfüllung ist niedrig; die Wahrscheinlichkeit der Schuldenrestrukturierung oder der Restrukturierung des Schuldenteils ist minimal.</span></a></p>
<p><a>Zweimal Preisträger von “Investor Awards”<span>“Investor Awards” wird sowohl der Gesellschaften als auch den individuellen Investoren für die größten Leistungen im Bereich der Kapitalanlage einhändigt. Im Jahr 2011 UFS IC gewann den Preis in der Nominierung “Transaktion des Jahres. Aufbringung der fremden Kapitalanlagen in den Gesellschaften des zweiten und dritten Rangs”, für die Aufbringung der Kapitalanlagen mit Hilfe von Anleihestrukturierung und Euroobligationenausgabe für die Gesellschaft “LenSpezSMU”. Im Jahr 2012 UFS IC wurde den Preisträger in der Spezialnominierung “Der beste Treuhandverwaltung auf den Märkten fixed-income CIS und ETFs & Mutual Funds (Gold)”.</span></a></p>
<p><a>Goldenes Diplom “für die Informationstransparenz”<span>Der allrussische Wettbewerb “Goldenes Diplom für die Informationstransparenz” wird durchgeführt, um die wirksame Zusammenarbeit zwischen russischen Medien, Staats - und Ortsbehörde und Geschäftsgemeinschaft zu unterstützen. Im Jahr 2012 UFS IC in den Rahmen des Wettbewerbes bekam das spezielle goldene Diplom “für die Informationstransparenz”.</span></a></p>
<p><a>Nationalpreisträger des “Finanzolympus”<span>Der Nationalpreis “Finanzolymp” ist der Berufspreis der die Erfolge der größten Gesellschaften auf dem russischen Finanzmarkt anmerkt. UFS IC wurde als die beste Gesellschaft in der Nominierung “Strategie der Kapitalanlage. Ergebnis und Erfolg” erkannt.</span></a></p>
<p><a>Preisträger von Spear&rsquo;s Awards<span>Spear&rsquo;s Russian Wealth Management Awards ist der erste jährliche Preis in Russland für die besten Teilnehmer von Private Banking, Vermögensverwaltung und verbundenen Industriezweigen. Im 2013 wurde UFS IC Presträger in der Nominierung “Der goldene Standard von Private Banking” für die Entwicklung und Förderung der Ideen der alternativen Kapitalanlagen.</span></a></p>
<p><a>Zweimal Preisträger von Cbonds Awards<span>Der jährliche Preis Cbonds Awards wird den größten russischen Investitionsbanken und Gesellschaften — den besten Teilnehmern des Schuldenmarktes überreicht. In 2014 nach den Ergebnissen der Abstimmung wurde UFS IC Preisträger in der Nominierung "Die meistgelesene Analytik auf dem Bondsmarkt". In 2013 nach den Ergebnissen der Abstimmung bekam UFS IC den Preis in den Nominierungen «Durchbruch des Jahres im Forschungsbereich» und “Der best Analyst im Bereich der festverzinslichen Wertpapiere”.</span></a></p></div>
	<? } ?>
	<? if($this->site_lang=='fr') { ?> 
<div class="legal_notice">
<p><a>Classement de fiabilité au niveau A, haut niveau de fiabilité (RA Expert)<span>“Expert RA” est la principale agence de notation de la Russie. Dans la liste de classement de l’agence il y a plus de 350 classements individuels en vigueur, y compris 85% du nombre total des classements de fiabilité. Le pronostic “stable” signifie la haute possibilité de préservation de classement au niveau actuel dans la perspective à moyen terme.</span></a></p>
<p><a>Classement de solvabilité selon l’échelle nationale “A” (AK &M)<span>Le classement AK &M est une estimation cohérente de la capacité de la compagnie d’investissement à accomplir complètement et à temps ses obligations. Le classement “A” signifie que la compagnie a un haut niveau de solvabilité. Le risque d’accomplissement inopportun des obligations est bas, la probabilité de restructuration de la dette ou de sa part est minimale.</span></a></p>
<p><a>Deux fois lauréat du prix “Investor Awards”<span>Le prix “Investor Awards” est décerné pour les acquis les plus importants dans le domaine de l'investissement tant aux compagnies qu’aux investisseurs individuels. En 2011 l’UFS IC a reçu le prix dans la nomination “La tractation de l’année . Attraction des investissements internationaux dans les compagnies de deuxième et de troisième rang à l’aide de la structuration de l’emprunt et de l’émission des euro-obligations pour la compagnie “LenSpetsSMOU”. En 2012 L’UFS IC a été lauréat du prix dans la nomination particulière “La meilleure gestion fudiciaire sur les marchés “fixed-income CIS et ETFs & Mutual Funds (Gold)”.</span></a></p>
<p><a>Diplôme d’or de la “transparence informationnelle”<span>Le concours national russe “Diplôme d’or de la transparence informationnelle” est organisé dans le but de soutenir l’interaction efficace entre les médias russes, les pouvoirs publics et municipaux et la communauté des affaires. En 2012 L’UFS IC dans le cadre du concours a reçu le diplôme d’or de la “transparence informationnelle.</span></a></p>
<p><a>Lauréat du prix national “Olympe financier”<span>Le prix national “Olympe financier” est un prix professionnel qui distingue chaque année les réussites des compagnies et des top-managers principaux qui travaillent sur le marché financier de la Russie. L’UFS IC a été reconnu comme la meilleure compagnie dans la nomination “Stratégie d’investissement. Résultat et réussite”</span></a></p>
<p><a>Lauréat du prix Spear&rsquo;s Awards<span>Spear&rsquo;s Russian Wealth Management Awards est le premier prix en Russie pour les meilleurs représentants de l&rsquo;industrie banking, gestion des richesses et des industries adjacentes. En 2013 l&rsquo;UFS IC est devenu lauréat du prix dans la catégorie "Le standard d&rsquo;or de l&rsquo;industrie private banking" pour le développement et la promotion des idées d&rsquo;investissements alternatifs.</span></a></p>
<p><a>Deux fois lauréat du prix Cbonds Awards<span>Le prix annuel Cbonds Awards est décerné aux plus importantes banques et compagnies russes d’investissement, étant les meilleurs participants du marché de dette. En 2014 à l’issue du vote l’UFS IC est devenu lauréat dans la catégorie "La recherche la plus lisible sur le marché obligataire". En 2013 à l’issue du vote l’UFS IC a reçu le prix dans les catégories «Decouverte de l’année dans la recherche» et « Le meilleur analyste sur le marché à revenu fixe ».</span></a></p>
	</div>
	<? } ?>
  </div>